spring:
  datasource:
    url: jdbc:h2:file:C:/MyLib/H2/myH2DB
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true



#logging:
#  level:
#    root: DEBUG

server:
  port: 9997
#
#web.config.cors: webMvc
#
#corses.list:
#  -
#    path-patterns:
#      - /**
#    allowed-origins:
#      - http://localhost:*
#    allowed-methods: GET,POST,HEAD,OPTIONS,PUT,DELETE,PATCH
#    allowed-headers:
#      - Authorization
#      - Content-Type
#      - X-Requested-With
#      - accept,Origin
#      - Access-Control-Request-Method
#      - Access-Control-Request-Headers
#    allowed-credentials: true
#    exposed-headers: Access-Control-Allow-Origin,Access-Control-Allow-Credentials
#    max-age: 86400